blank_issues_enabled: false
contact_links:
    - name: Feature Request
      url: https://github.com/RooVetGit/Magic-Code/discussions/categories/feature-requests
      about: Share and vote on feature requests for Magic Code
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=RooVeterinaryInc.magic-code&ssr=false#review-details
      about: Enjoying Magic Code? Leave a review here!
